Repository US-EPA-CAMD/easey-facilities-api, pull requests merged in 2021-01, with the labels that each got.

#19 Feature/617 update facilities readme
  README.md
Labels: Datateers, Tech Team, documentation

#22 feature/jest-unit-test-coverage-sonar-scan
  .github/workflows/develop-branch.yml
  .github/workflows/feature-branch.yml
  package-lock.json
  package.json
  sonar-project.properties
  src/facilities/facilities.controller.spec.ts
  src/facilities/facilities.controller.ts
  src/facilities/facilities.service.spec.ts
  src/facilities/facilities.service.ts
  src/utils/response.headers.ts
  test-report.xml
Labels: Tech Team

#23 Feature/632 configure easey facilities api unit tests
  .github/workflows/develop-branch.yml
  .github/workflows/feature-branch.yml
  .github/workflows/release-branch.yml
  nest-cli.json
  package-lock.json
  package.json
  src/app.module.ts
  src/dtos/contacts/contact-person.dto.ts
  src/dtos/contacts/contact-unit.dto.ts
  src/dtos/contacts/get-contacts.dto.ts
  src/dtos/facility.dto.ts
  src/dtos/facility.params.dto.ts
  src/dtos/filters/facilities-filter.dto.ts
  src/dtos/filters/units-filter.dto.ts
  src/dtos/pagination.dto.ts
  src/dtos/unit.dto.ts
  src/dtos/units/get-unit-by-id.dto.ts
  src/dtos/units/get-units.dto.ts
  src/dtos/units/unit-ce-param.dto.ts
  src/dtos/units/unit-fuel.dto.ts
  src/dtos/units/unit-program.dto.ts
  src/entities/contact-relation.entity.ts
  src/entities/person.entity.ts
  src/entities/plant-person.entity.ts
  src/entities/plant.entity.ts
  src/entities/unit-boiler-type.entity.ts
  src/entities/unit-capacity.entity.ts
  src/entities/unit-control.entity.ts
  src/entities/unit-fuel.entity.ts
  src/entities/unit-generator.entity.ts
  src/entities/unit-op-status.entity.ts
  src/entities/unit-owner.entity.ts
  src/entities/unit-program.entity.ts
  src/entities/unit-stack-configuration.ts
  src/entities/unit.entity.ts
  src/main.ts
  src/maps/facility.map.ts
  src/maps/unit.map.ts
  src/routes.ts
  src/units/units.controller.ts
  src/units/units.module.ts
  src/units/units.repository.ts
  src/units/units.service.ts
  test-report.xml
Labels: DevOps, Tech Team
